name: Run Main Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  unit-tests:
    needs: build
    uses: ./.github/workflows/unit-tests.yml
    secrets: inherit

  # security:
  #   needs: build
  #   uses: ./.github/workflows/security-test.yml
  #   secrets: inherit

  # test-model-evals:
  #   needs: unit-tests
  #   uses: ./.github/workflows/model-evals.yml
  #   secrets: inherit

  push-to-ecr:
    needs: unit-tests
    uses: ./.github/workflows/push-to-ecr.yml
    secrets: inherit

  deploy-to-ecs:
    needs: push-to-ecr
    uses: ./.github/workflows/deploy-to-ecs.yml
    secrets: inherit
    with:
      sha: ${{ needs.outputs.push-to-ecr.sha }} # Pass image URI as input
